image:
  imagerepo: gcr.io/jenkinsxio/jx-tenant-service
<<<<<<< HEAD
  imagetag: 0.0.155
=======
  imagetag: 0.0.152
>>>>>>> feat: add refresh github app cron job
refreshJobrb:
  enabled: true
refreshJobsa:
  enabled: true
refreshRole:
  enabled: true
<<<<<<< HEAD
refreshJob:
  enabled: true
  command:
    - jxt
=======
command:
  - jxt
refreshJob:
  enabled: true
>>>>>>> feat: add refresh github app cron job
  args:
    - get
    - github
    - token
  env:
    JX_REQUIREMENT_DOMAIN_ISSUER_URL: "{{ .Requirements.ingress.domainIssuerURL }}"
  schedule: 30 * * * *
service:
  enabled: false
updatejob:
  enabled: false
basicAuthSecret:
  enabled: false
cloudsqlsa:
  enabled: false
deployment:
  enabled: false
rolebinding:
  enabled: false
saasSecret:
  enabled: false
secret:
  enabled: false
serviceAccount:
  enabled: false
wildcardSecret:
  enabled: false
