{{- if .Requirements.githubApp.enabled }}
enabled: true
{{- else }}
enabled: false
{{- end }}

{{- if hasKey .Requirements.cluster "clusterName" }}
serviceAccount: "{{ .Requirements.cluster.clusterName }}-jb"
{{- end }}
