dependencies:
  - alias: tekton
    name: tekton
    repository: http://chartmuseum.jenkins-x.io
  - condition: prow.enabled
    alias: prow
    name: prow
    repository: http://chartmuseum.jenkins-x.io
  - condition: lighthouse.enabled
    alias: lighthouse
    name: lighthouse
    repository: http://chartmuseum.jenkins-x.io
  - name: jenkins-x-platform
    repository: http://chartmuseum.jenkins-x.io
  - condition: external-dns.enabled
    name: external-dns
    repository: https://charts.bitnami.com/bitnami
#- condition: chartmuseum.enabled
#  name: chartmuseum
#  repository: http://chartmuseum.jenkins-x.io
  - name: jx-app-sso
    repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    version: 0.0.14
  - name: jx-app-ui
    repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    version: 0.0.792
